### ISSUE TITLE
These scripts don't work for the latest openBalena release.

### ISSUE THREAD

**Issue by Zebble** [balena-io-examples/staged-releases#30]
I had a problem with a Fleet being pinned to a release in openBalena.  I tried to use these scripts to remedy that but all of them came back with a "Cannot Patch ..." error.

It appears that openBalena's API's have changed.  Luckily, changing "v5" to "v6" in the scripts I needed, solved the issue.  Balena Cloud seems to be smarter in that it will continue to accept v5 API calls without a hitch.  openBalena is more strict.

Hopefully this helps anyone else trying to use these scripts with openBalena.

**Comment by thgreasi** [comment]
Hi,

BalenaCloud keeps supporting all previous versions of our model/endpoints and forward translates them to the latest model version.
On the other hand openBalena only supports the latest version, which at this point is v6.
Thanks for reporting this, we will get this fixed properly soon.

Kind regards,
Thodoris
